# Continuous Integration workflow for checking for common code issues
name: Lint CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install and Lint
        run: |
          npm ci
          npm run lint
